var data = [{
  'image': '../assets/images/1.jpg',  
  'name': 'Axel',
  'address': 'No address',
  'phone': 'No number yet',
  'country': 'Peru',
},
{
  'image': '../assets/images/2.jpg',  
  'name': 'Lele',
  'address': 'No address',
  'phone': 'No number yet',
  'country': 'France',
},
{
  'image': '../assets/images/3.jpg',  
  'name': 'Twan',
  'address': 'No address',
  'phone': 'No number yet',
  'country': 'Spain',
},
{
  'image': '../assets/images/4.jpg',  
  'name': 'Alabama',
  'address': 'No address',
  'phone': 'No number yet',
  'country': 'Germany',
},
{
  'image': '../assets/images/5.jpg',  
  'name': 'Solange',
  'address': 'No address',
  'phone': 'No number yet',
  'country': 'Italy',
},
{
  'image': '../assets/images/6.jpg',  
  'name': 'Emma',
  'address': 'No address',
  'phone': 'No number yet',
  'country': 'Portugal',
},
{
  'image': '../assets/images/7.jpg',  
  'name': 'Solomon',
  'address': 'No address',
  'phone': 'No number yet',
  'country': 'England',
}];